import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name="CommissionLevel", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("code",models.CharField(max_length=1,unique=True,verbose_name="سطح")),("performance_rate",models.PositiveIntegerField(verbose_name="ضریب عملکرد")),("violation_rate",models.PositiveIntegerField(verbose_name="ضریب تخلف")),("morning_rate",models.DecimalField(decimal_places=2,default=1,max_digits=8,verbose_name="ضریب صبح"))]),
      migrations.CreateModel(name="Department", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=100,unique=True,verbose_name="نام بخش")),("is_active",models.BooleanField(default=True,verbose_name="فعال"))]),
      migrations.CreateModel(name="Target", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=100,verbose_name="عنوان")),("points",models.PositiveIntegerField(verbose_name="امتیاز هدف")),("reward",models.PositiveBigIntegerField(default=0,verbose_name="پاداش")),("is_active",models.BooleanField(default=True,verbose_name="فعال"))], options={"ordering":["points"]}),
      migrations.CreateModel(name="ViolationRule", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("code",models.CharField(max_length=20,unique=True,verbose_name="کد")),("title",models.CharField(max_length=180,verbose_name="عنوان")),("first_points",models.PositiveIntegerField(verbose_name="مرتبه اول")),("second_points",models.PositiveIntegerField(verbose_name="مرتبه دوم")),("third_points",models.PositiveIntegerField(verbose_name="مرتبه سوم")),("is_active",models.BooleanField(default=True,verbose_name="فعال"))]),
      migrations.CreateModel(name="Employee", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("employee_code",models.CharField(max_length=20,unique=True,verbose_name="کد کارمند")),("full_name",models.CharField(max_length=150,verbose_name="نام و نام خانوادگی")),("role",models.CharField(choices=[("MANAGER","مدیر"),("SUPERVISOR","سرپرست"),("EMPLOYEE","کارمند")],default="EMPLOYEE",max_length=12,verbose_name="نقش")),("start_date",models.DateField(blank=True,null=True,verbose_name="تاریخ شروع")),("is_active",models.BooleanField(default=True,verbose_name="فعال")),("departments",models.ManyToManyField(blank=True,related_name="employees",to="core.department")),("level",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="employees",to="core.commissionlevel")),("user",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="employee",to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name="ActivityType", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("code",models.CharField(max_length=20,unique=True,verbose_name="کد")),("title",models.CharField(max_length=150,verbose_name="عنوان")),("category",models.CharField(max_length=100,verbose_name="گروه")),("unit",models.CharField(default="تعداد",max_length=50,verbose_name="واحد")),("points_per_unit",models.DecimalField(decimal_places=2,default=1,max_digits=10,verbose_name="امتیاز هر واحد")),("frequency",models.CharField(choices=[("DAILY","روزانه"),("WEEKLY","هفتگی"),("ADHOC","موردی")],default="ADHOC",max_length=10,verbose_name="تناوب")),("requires_approval",models.BooleanField(default=True,verbose_name="نیازمند تأیید")),("requires_evidence",models.BooleanField(default=False,verbose_name="نیازمند مدرک")),("is_active",models.BooleanField(default=True,verbose_name="فعال")),("departments",models.ManyToManyField(blank=True,related_name="activity_types",to="core.department"))]),
      migrations.CreateModel(name="Activity", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("activity_date",models.DateField(verbose_name="تاریخ فعالیت")),("quantity",models.DecimalField(decimal_places=2,max_digits=12,validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],verbose_name="مقدار")),("points_snapshot",models.DecimalField(decimal_places=2,max_digits=10,verbose_name="امتیاز هر واحد هنگام ثبت")),("description",models.TextField(blank=True,verbose_name="توضیحات")),("evidence",models.FileField(blank=True,upload_to="evidence/%Y/%m/",verbose_name="مدرک")),("status",models.CharField(choices=[("PENDING","در انتظار"),("APPROVED","تأییدشده"),("REJECTED","ردشده"),("NEEDS_EDIT","نیازمند اصلاح")],default="PENDING",max_length=12,verbose_name="وضعیت")),("review_note",models.TextField(blank=True,verbose_name="یادداشت بررسی")),("reviewed_at",models.DateTimeField(blank=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True)),("activity_type",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="activities",to="core.activitytype")),("employee",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="activities",to="core.employee")),("reviewed_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="reviewed_activities",to=settings.AUTH_USER_MODEL)),("submitted_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="submitted_activities",to=settings.AUTH_USER_MODEL))], options={"ordering":["-activity_date","-created_at"]}),
      migrations.CreateModel(name="Violation", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("violation_date",models.DateField(verbose_name="تاریخ")),("occurrence",models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1),django.core.validators.MaxValueValidator(3)],verbose_name="مرتبه")),("points_snapshot",models.PositiveIntegerField(verbose_name="امتیاز تخلف")),("description",models.TextField(verbose_name="شرح")),("created_at",models.DateTimeField(auto_now_add=True)),("employee",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="violations",to="core.employee")),("recorded_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="recorded_violations",to=settings.AUTH_USER_MODEL)),("rule",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="violations",to="core.violationrule"))], options={"ordering":["-violation_date","-created_at"]}),
    ]

