# Generated by Django 5.1.7 on 2026-08-29 07:17

from django.db import migrations, models


def migrate_existing_activity_types(apps, schema_editor):
    ActivityType = apps.get_model("core", "ActivityType")

    # Existing non-fixed scoring methods historically depended on a raw value.
    # Treat that value as measurable quantity after the new workflow migration.
    ActivityType.objects.filter(
        scoring_method__in=["QUANTITY_MULTIPLIER", "DIRECT_VALUE"]
    ).update(requires_quantity=True)


def reverse_existing_activity_types(apps, schema_editor):
    ActivityType = apps.get_model("core", "ActivityType")
    ActivityType.objects.update(requires_quantity=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت فعالیت به دقیقه'),
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت پایان'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت شروع'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='requires_quantity',
            field=models.BooleanField(default=False, verbose_name='نیازمند ثبت مقدار'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='requires_time_tracking',
            field=models.BooleanField(default=True, verbose_name='نیازمند ثبت ساعت شروع و پایان'),
        ),
        migrations.RunPython(
            migrate_existing_activity_types,
            reverse_existing_activity_types,
        ),
    ]
