# Generated by Django 5.1.7 on 2026-09-28 10:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_violation_base_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineactivitytype',
            name='unit_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='تیک = ۱ × ضریب. عدد = تعداد × ضریب.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='ضریب تبدیل به واحد عملکرد'),
        ),
        migrations.AlterField(
            model_name='violationrule',
            name='recurrence_window',
            field=models.CharField(choices=[('SAME_MONTH', 'همان ماه'), ('ROLLING_30_DAYS', '۳۰ روز گذشته'), ('MANUAL_PERIOD', 'دوره قابل تنظیم')], default='SAME_MONTH', help_text='تکرار در همان ماه شمسی، برای همان کارمند و همان قانون، خودکار حساب می\u200cشود.', max_length=20, verbose_name='بازه محاسبه تکرار'),
        ),
    ]
