# Generated by Django 5.1.7 on 2026-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_violation_repeat_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationrule',
            name='base_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='امتیاز بار اول. بارهای بعد تا بار سوم در «چند برابر» ضرب می\u200cشوند.', verbose_name='ضریب'),
        ),
    ]
