# Generated by Django 5.1.7 on 2026-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_violationrule_base_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationrule',
            name='base_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='امتیاز بار اول. از بار دوم به بعد این عدد در «چند برابر» ضرب می\u200cشود.', verbose_name='ضریب'),
        ),
        migrations.AlterField(
            model_name='violationrule',
            name='repeat_multiplier',
            field=models.PositiveIntegerField(default=2, help_text='از بار دوم به بعد، امتیاز = ضریب × این عدد.', verbose_name='چند برابر در تکرار'),
        ),
    ]
