# Generated by Django 5.1.7 on 2026-09-29 14:45

import django.db.models.deletion
from django.db import migrations, models


def seed_branches(apps, schema_editor):
    Branch = apps.get_model("core", "Branch")
    specs = [
        (1, "دفتر اینترنتی"),
        (2, "فروشگاه ساری"),
        (3, "فروشگاه گرگان"),
        (4, "فروشگاه کاپری"),
    ]
    for sort_order, name in specs:
        Branch.objects.get_or_create(name=name, defaults={"sort_order": sort_order, "is_active": True})
    home = Branch.objects.get(name="فروشگاه ساری")
    for model_name in (
        "Department",
        "CommissionLevel",
        "Shift",
        "LineActivityType",
        "ViolationRule",
        "DailyShiftLog",
        "LineShiftPerformance",
        "Violation",
    ):
        model = apps.get_model("core", model_name)
        model.objects.filter(branch__isnull=True).update(branch=home)
    Employee = apps.get_model("core", "Employee")
    Employee.objects.filter(role="MANAGER").update(is_super_admin=True, branch=None)
    Employee.objects.filter(is_super_admin=False, branch__isnull=True).update(branch=home)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_violation_coefficient_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='نام شعبه')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعبه\u200cها',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='commissionlevel',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='employee',
            name='is_super_admin',
            field=models.BooleanField(default=False, verbose_name='سوپر ادمین'),
        ),
        migrations.AlterField(
            model_name='commissionlevel',
            name='code',
            field=models.CharField(max_length=1, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام بخش'),
        ),
        migrations.AlterField(
            model_name='lineactivitytype',
            name='title',
            field=models.CharField(max_length=120, verbose_name='نام فعالیت'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='code',
            field=models.CharField(max_length=20, verbose_name='کد شیفت'),
        ),
        migrations.AlterField(
            model_name='violationrule',
            name='code',
            field=models.CharField(max_length=20, verbose_name='کد'),
        ),
        migrations.AddField(
            model_name='commissionlevel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='dailyshiftlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='lineactivitytype',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='lineshiftperformance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='shift',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='violation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='violationrule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch', verbose_name='شعبه'),
        ),
        migrations.RunPython(seed_branches, migrations.RunPython.noop),
        # قیدهای یکتا در 0034 هستند. UPDATE و ALTER TABLE در یک تراکنش
        # روی PostgreSQL خطای pending trigger events می‌دهد.
    ]
